### ISSUE TITLE
"temporary value dropped while borrowed" in the derive macro `SerializeRawFields`

### ISSUE THREAD

**Issue by vittorius** [LasterAlex/teloxide_tests#9] opened 2024-08-22 19:19 UTC
**What went wrong:**
Could not compile due to an error:

```
error[E0716]: temporary value dropped while borrowed
  --> /Users/vittorius/.cargo/registry/src/index.crates.io-6f17d22bba15001f/teloxide_tests-0.1.3/src/server/routes/send_animation.rs:79:37
   |
79 | #[derive(Debug, Clone, Deserialize, SerializeRawFields)]
   |                                     ^^^^^^^^^^^^^^^^^-
   |                                     |                |
   |                                     |                temporary value is freed at the end of this statement
   |                                     creates a temporary value which is freed while still in use
   |                                     borrow later used here
   |
   = note: this error originates in the derive macro `SerializeRawFields` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider using a `let` binding to create a longer lived value
```

(this error occurs for all mentions of `SerializeRawFields` in `send_animation.rs`, `send_audio.rs`, and other `send_*.rs` files).

**To Reproduce:**
- Create a binary crate project
- Add `teloxide_tests = "0.1.3"` to the Cargo.toml
- Try running `cargo build`

**Additional context:**

_**Cargo.toml**_

```
[package]
name = "adnow_lunch_bot"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
shuttle-runtime = "0.46.0"
teloxide = { version = "0.12", features = ["macros"] }
log = "0.4"
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
anyhow = { version = "1.0.81", features = ["backtrace"] }
shuttle-persist = "0.46.0"
rand = "0.8.5"
serde = "1.0.203"
serde_json = "1.0.117"
axum = "0.7.5"
shuttle-axum = "0.46.0"
shuttle-shared-db = { version = "0.46.0", features = ["postgres", "sqlx"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-rustls", "chrono"] }
teloxide_tests = "0.1.3"
mockall = "0.13.0"
```

_**rust-toolchain.toml:**_

```
[toolchain]
channel = "1.76-aarch64-apple-darwin"
```

**Meta:**
`teloxide_tests` version: 0.1.3
`teloxide` version: 0.12

**Comment by LasterAlex** [comment] 2024-08-22 22:04
Reproduced, seems to be a rust version issue, 1.77 and 1.78 don't work too, but 1.79 does
Thanks for pointing this out! I will try to lower the minimal supported Rust version to the one that `teloxide` has (1.70), but for now you can change the toolchain to 1.79 or 1.80 (rust doesn't have breaking changes, so it will be just a number shift)

I will keep this issue open for the msrv problem, but it is fixable without it, so i'll focus on migrating to 0.13.0 first (blocked by some deserialization issue that i fixed on `teloxide` master, but it isn't yet released)
Github version with broken reply_markup coming soon though

**Comment by LasterAlex** [comment] 2024-09-20 15:05
Migrating to 0.13.0 lowered the minimal rust version to 1.72, good enough

**Closed by LasterAlex** 2024-09-20 15:05 UTC
Labels: bug, good first issue
